# Generated by Django 4.2.6 on 2023-10-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('notstarted', 'notstarted'), ('inprogress', 'inprogress'), (',completed]', ',completed]')], default='notstarted', max_length=20)),
            ],
        ),
    ]
